// export { Navbar } from './navbar'
export { Hero } from './hero'
// export { HowItWorks } from './how-it-works'
// export { Features } from './features'
// export { Stats } from './stats'
// export { Testimonials } from './testimonials'
// export { CTA } from './cta'
// export { Footer } from './footer'
